name: CI wallet

on:
  pull_request:
    branches: ["main"]
    paths:
      - wallet/**

jobs:
  core:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.5

      - name: Install dependencies
        working-directory: ./wallet
        run: go mod download

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run format
        working-directory: ./wallet
        run: make format

      - name: Run lint
        working-directory: ./wallet
        run: make lint

      - name: Run tests
        working-directory: ./wallet
        run: make test
